version: '3.8'
services:

  db_mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  liquibase_mysql:
    image: liquibase/liquibase:4.26
    container_name: liquibase_mysql
    environment:
      - "INSTALL_MYSQL=true"
    volumes:
      - ./dbschema:/liquibase/changelog
    command: [
        'update',
        '--changeLogFile=changelog/changelog1.0.xml',
        '--url=jdbc:mysql://db_mysql:3306/${MYSQL_DATABASE}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false',
        '--username=root',
        '--password=${MYSQL_ROOT_PASSWORD}'
      ]
    depends_on: 
      db_mysql:
        condition: service_healthy

  db_pgsql:
    image: postgres:12.18
    container_name: pgsql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  liquibase_pgsql:
    image: liquibase/liquibase:4.26
    container_name: liquibase_pgsql
    volumes:
      - ./dbschema:/liquibase/changelog
    command: [
        'update',
        '--changeLogFile=changelog/changelog1.0.xml',
        '--url=jdbc:postgresql://db_pgsql:5432/${POSTGRES_DB}',
        '--username=postgres',
        '--password=${POSTGRES_PASSWORD}'
      ]
    depends_on: 
      db_pgsql:
        condition: service_healthy

  db_mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql
    cap_add: 
      - SYS_PTRACE
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y 
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}

  liquibase_mssql:
    image: liquibase/liquibase:4.26
    container_name: liquibase_mssql
    volumes:
      - ./dbschema:/liquibase/changelog
    command: [
        '--changeLogFile=changelog/changelog1.0.xml',
        '--url=jdbc:sqlserver://db_mssql:1433;databaseName=master;encrypt=true;trustServerCertificate=true',
        '--username=sa',
        '--password=${MSSQL_PASSWORD}',
        'update'
      ]
    depends_on: 
      db_mssql:
        condition: service_started
      liquibase_mysql:
        condition: service_started
      liquibase_pgsql:
        condition: service_started